# Site settings
title: 
description: A blog.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Krishna K
user_description: ''
user_title: Machine Learning Engineer
email: krishnakalyan3@gmail.com
twitter_username: krishnakalyan3
github_username:  krishnakalyan3

# Google-analytics
google-analytics:
  id: "UA-28463515-7"

exclude: ['package.json', 'src' , 'node_modules']
